/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {Route as rootRouteImport} from './routes/__root';
import {Route as PublicRouteRouteImport} from './routes/_public/route';
import {Route as _pathlessLayoutRouteRouteImport} from './routes/__pathlessLayout/route';
import {Route as PublicIndexRouteImport} from './routes/_public/index';
import {Route as PublicLoginRouteImport} from './routes/_public/login';
import {Route as _pathlessLayoutHomeRouteImport} from './routes/__pathlessLayout/home';
import {Route as PublicOnboardingIndexRouteImport} from './routes/_public/onboarding/index';
import {Route as PublicOnboardingSuccessRouteImport} from './routes/_public/onboarding/success';

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const _pathlessLayoutRouteRoute = _pathlessLayoutRouteRouteImport.update({
  id: '/__pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any);
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any);
const _pathlessLayoutHomeRoute = _pathlessLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _pathlessLayoutRouteRoute,
} as any);
const PublicOnboardingIndexRoute = PublicOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => PublicRouteRoute,
} as any);
const PublicOnboardingSuccessRoute = PublicOnboardingSuccessRouteImport.update({
  id: '/onboarding/success',
  path: '/onboarding/success',
  getParentRoute: () => PublicRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  '/home': typeof _pathlessLayoutHomeRoute;
  '/login': typeof PublicLoginRoute;
  '/': typeof PublicIndexRoute;
  '/onboarding/success': typeof PublicOnboardingSuccessRoute;
  '/onboarding': typeof PublicOnboardingIndexRoute;
}
export interface FileRoutesByTo {
  '/home': typeof _pathlessLayoutHomeRoute;
  '/login': typeof PublicLoginRoute;
  '/': typeof PublicIndexRoute;
  '/onboarding/success': typeof PublicOnboardingSuccessRoute;
  '/onboarding': typeof PublicOnboardingIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/__pathlessLayout': typeof _pathlessLayoutRouteRouteWithChildren;
  '/_public': typeof PublicRouteRouteWithChildren;
  '/__pathlessLayout/home': typeof _pathlessLayoutHomeRoute;
  '/_public/login': typeof PublicLoginRoute;
  '/_public/': typeof PublicIndexRoute;
  '/_public/onboarding/success': typeof PublicOnboardingSuccessRoute;
  '/_public/onboarding/': typeof PublicOnboardingIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/home' | '/login' | '/' | '/onboarding/success' | '/onboarding';
  fileRoutesByTo: FileRoutesByTo;
  to: '/home' | '/login' | '/' | '/onboarding/success' | '/onboarding';
  id:
    | '__root__'
    | '/__pathlessLayout'
    | '/_public'
    | '/__pathlessLayout/home'
    | '/_public/login'
    | '/_public/'
    | '/_public/onboarding/success'
    | '/_public/onboarding/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  _pathlessLayoutRouteRoute: typeof _pathlessLayoutRouteRouteWithChildren;
  PublicRouteRoute: typeof PublicRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PublicRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/__pathlessLayout': {
      id: '/__pathlessLayout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof _pathlessLayoutRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public/': {
      id: '/_public/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PublicIndexRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/_public/login': {
      id: '/_public/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof PublicLoginRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/__pathlessLayout/home': {
      id: '/__pathlessLayout/home';
      path: '/home';
      fullPath: '/home';
      preLoaderRoute: typeof _pathlessLayoutHomeRouteImport;
      parentRoute: typeof _pathlessLayoutRouteRoute;
    };
    '/_public/onboarding/': {
      id: '/_public/onboarding/';
      path: '/onboarding';
      fullPath: '/onboarding';
      preLoaderRoute: typeof PublicOnboardingIndexRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/_public/onboarding/success': {
      id: '/_public/onboarding/success';
      path: '/onboarding/success';
      fullPath: '/onboarding/success';
      preLoaderRoute: typeof PublicOnboardingSuccessRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
  }
}

interface _pathlessLayoutRouteRouteChildren {
  _pathlessLayoutHomeRoute: typeof _pathlessLayoutHomeRoute;
}

const _pathlessLayoutRouteRouteChildren: _pathlessLayoutRouteRouteChildren = {
  _pathlessLayoutHomeRoute: _pathlessLayoutHomeRoute,
};

const _pathlessLayoutRouteRouteWithChildren = _pathlessLayoutRouteRoute._addFileChildren(
  _pathlessLayoutRouteRouteChildren,
);

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute;
  PublicIndexRoute: typeof PublicIndexRoute;
  PublicOnboardingSuccessRoute: typeof PublicOnboardingSuccessRoute;
  PublicOnboardingIndexRoute: typeof PublicOnboardingIndexRoute;
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicOnboardingSuccessRoute: PublicOnboardingSuccessRoute,
  PublicOnboardingIndexRoute: PublicOnboardingIndexRoute,
};

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(PublicRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  _pathlessLayoutRouteRoute: _pathlessLayoutRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
