/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {Route as rootRouteImport} from './routes/__root';
import {Route as LoginRouteImport} from './routes/login';
import {Route as _pathlessLayoutRouteRouteImport} from './routes/__pathlessLayout/route';
import {Route as IndexRouteImport} from './routes/index';
import {Route as _pathlessLayoutHomeRouteImport} from './routes/__pathlessLayout/home';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const _pathlessLayoutRouteRoute = _pathlessLayoutRouteRouteImport.update({
  id: '/__pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const _pathlessLayoutHomeRoute = _pathlessLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _pathlessLayoutRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/home': typeof _pathlessLayoutHomeRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/home': typeof _pathlessLayoutHomeRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/__pathlessLayout': typeof _pathlessLayoutRouteRouteWithChildren;
  '/login': typeof LoginRoute;
  '/__pathlessLayout/home': typeof _pathlessLayoutHomeRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/login' | '/home';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/login' | '/home';
  id: '__root__' | '/' | '/__pathlessLayout' | '/login' | '/__pathlessLayout/home';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  _pathlessLayoutRouteRoute: typeof _pathlessLayoutRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/__pathlessLayout': {
      id: '/__pathlessLayout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof _pathlessLayoutRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/__pathlessLayout/home': {
      id: '/__pathlessLayout/home';
      path: '/home';
      fullPath: '/home';
      preLoaderRoute: typeof _pathlessLayoutHomeRouteImport;
      parentRoute: typeof _pathlessLayoutRouteRoute;
    };
  }
}

interface _pathlessLayoutRouteRouteChildren {
  _pathlessLayoutHomeRoute: typeof _pathlessLayoutHomeRoute;
}

const _pathlessLayoutRouteRouteChildren: _pathlessLayoutRouteRouteChildren = {
  _pathlessLayoutHomeRoute: _pathlessLayoutHomeRoute,
};

const _pathlessLayoutRouteRouteWithChildren = _pathlessLayoutRouteRoute._addFileChildren(
  _pathlessLayoutRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _pathlessLayoutRouteRoute: _pathlessLayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
